### ISSUE TITLE
chroot: can't execute 'chroot.sh': No such file or directory

### ISSUE THREAD

**Issue by prateek-adhikaree** [crytic/solc-select#12] opened 2019-04-19 17:44 UTC
My dev machine is Ubuntu 18.04 and Docker version 18.09.5

I tried to install solc-select from source. The installation went through correctly. But when I tried to check the versions I had the following error:
`$ solc --version`
> mount: mounting /usr/bin on /workdir/usr/bin failed: Permission denied
> mount: mounting /bin on /workdir/bin failed: Permission denied
> mount: mounting /dev on /workdir/proc failed: Permission denied
> mount: mounting /proc on /workdir/dev failed: Permission denied
> mount: mounting /sys on /workdir/sys failed: Permission denied
> chroot: can't execute 'chroot.sh': No such file or directory

I uninstalled my solc installation and tried this again but had the same result.

Next, I uninstalled solc-select and ran the docker version. I had to update chmod for solc. But even after that I ran into the above errors when I tried to check the version again.

**Comment by ESultanik** [comment] 2019-04-22 11:21
I believe certain host system configurations require the `—priveleged` flag to be added to the Docker call. I will try to reproduce today and add that to the script if it fixes the problem.

**Comment by sobolev-igor** [comment] 2019-04-26 12:30
Hi! I have the same problem. Installation finishes with
```
Installed solc to /usr/local/bin/solc
```
And then I can't do anything with `solc`.

**Comment by ESultanik** [comment] 2019-04-26 13:05
We're working on a clean solution for this. We did not originally intend `solc-select` to be used on Linux since all of the official binaries are released on Linux. We will likely release a fix to the scripts to fix this problem as a stopgap, but in the long run we will be releasing an install script specifically for Linux that does not require Docker at all.

**Comment by sobolev-igor** [comment] 2019-04-26 13:39
OK, thanks! Looking forward for updates on this issue!

**Comment by prateek-adhikaree** [comment] 2019-05-19 17:06
@ESultanik, Any updates on the issue??

**Comment by montyly** [comment] 2019-06-19 07:25
I pushed an temporary fix for Ubuntu on the branch https://github.com/crytic/solc-select/tree/dev-fix-ubuntu

To install solc-select from it, run:
``` 
$ git clone https://github.com/trailofbits/solc-select.git
$ cd solc-select
$ git checkout dev-fix-ubuntu
$ docker build -t trailofbits/solc-select:latest .
$ bin/solc --install
```

**Comment by sobolev-igor** [comment] 2019-06-19 10:07
Thanks so much! 

Works great on Ubuntu 18.04.2 LTS

**Comment by SlightlyCyborg** [comment] 2019-07-31 21:33
Hmm. Sadly this does not work for Arch.

**Comment by montyly** [comment] 2019-10-28 08:30
I believe this was fixed with https://github.com/crytic/solc-select/issues/19?

**Comment by olugbokikisemiu** [comment] 2019-11-05 13:26
Hi, i followed this step to install solc on mac but i keep getting bash: line 51: /usr/bin/solc: Operation not permitted... Any help please?
```git clone https://github.com/trailofbits/solc-select.git
$ cd solc-select
$ docker build -t trailofbits/solc-select:latest .
$ bin/solc --install

**Comment by disconnect3d** [comment] 2020-12-21 13:28
I believe this is old enough to be closed. Let us know if the problem persists to anyone (probably creating another issue).

**Closed by disconnect3d** 2020-12-21 13:28 UTC
Labels: bug

**Comment by Satoshi-Kusumoto** [comment] 2021-01-18 03:59
I also followed the step to install solc on mac and when I run `solc` I got the same problem
chroot: can't execute 'chroot.sh': No such file or directory
```
$ cd solc-select
$ docker build -t trailofbits/solc-select:latest .
$ bin/solc --install
```

**Comment by arcz** [comment] 2021-01-18 12:58
@Satoshi-Kusumoto please try out the new `solc-select`, it doesn't require docker https://github.com/crytic/solc-select#experimental-solc-select

**Comment by reem** [comment] 2021-02-04 20:58
Still seeing this exact issue today trying to install following default instructions in the README on macOS. It simply says that solc is installed but commands such as `solc --versions` all just fail with the titular error message

**Comment by canokaue** [comment] 2021-02-06 02:52
Having the same problem on macOS, no way of getting it to work. @arcz I suggest this is isso is reopened.

**Comment by arcz** [comment] 2021-02-06 11:59
@reem @canokaue have you tried this https://github.com/crytic/solc-select#experimental-solc-select? we will be most likely removing the current Docker set up anyway as it turned out to be problematic

**Comment by canokaue** [comment] 2021-02-07 23:41
@arcz tried it and got the same error, I don't think it's a Docker issue (changing to a more convenient distribution method is interesting regardless).

**Comment by arcz** [comment] 2021-02-08 13:07
that shouldn't happen, the new solc-select doesn't use chroot anywhere, are you sure you don't have the old one still in PATH?

**Comment by canokaue** [comment] 2021-02-08 21:08
Yep, that works great, my bad. Thanks for the help mate.
